package mrs.infrastructure.datasource.autogen.reserve;

import mrs.domain.model.autogen.reserve.予約;
import org.apache.ibatis.annotations.*;

public interface 予約Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve.予約
     *
     * @mbg.generated
     */
    @Delete({
            "delete from reserve.予約",
            "where 予約番号 = #{予約番号,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer 予約番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve.予約
     *
     * @mbg.generated
     */
    @Insert({
            "insert into reserve.予約 (予約番号, 予約終了時間, ",
            "予約開始時間, 予約日, 会議室番号, ",
            "会員番号, 登録日時)",
            "values (#{予約番号,jdbcType=INTEGER}, #{予約終了時間,jdbcType=TIME}, ",
            "#{予約開始時間,jdbcType=TIME}, #{予約日,jdbcType=DATE}, #{会議室番号,jdbcType=INTEGER}, ",
            "#{会員番号,jdbcType=VARCHAR}, #{登録日時,jdbcType=TIMESTAMP})"
    })
    int insert(予約 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve.予約
     *
     * @mbg.generated
     */
    int insertSelective(予約 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve.予約
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "予約番号, 予約終了時間, 予約開始時間, 予約日, 会議室番号, 会員番号, 登録日時",
            "from reserve.予約",
            "where 予約番号 = #{予約番号,jdbcType=INTEGER}"
    })
    @ResultMap("mrs.infrastructure.datasource.autogen.reserve.予約Mapper.BaseResultMap")
    予約 selectByPrimaryKey(Integer 予約番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve.予約
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(予約 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve.予約
     *
     * @mbg.generated
     */
    @Update({
            "update reserve.予約",
            "set 予約終了時間 = #{予約終了時間,jdbcType=TIME},",
            "予約開始時間 = #{予約開始時間,jdbcType=TIME},",
            "予約日 = #{予約日,jdbcType=DATE},",
            "会議室番号 = #{会議室番号,jdbcType=INTEGER},",
            "会員番号 = #{会員番号,jdbcType=VARCHAR},",
            "登録日時 = #{登録日時,jdbcType=TIMESTAMP}",
            "where 予約番号 = #{予約番号,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(予約 record);
}
