package mrs.domain.model.autogen.service_user;

import java.util.Date;

public class 会員 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_user.会員.会員番号
     *
     * @mbg.generated
     */
    private String 会員番号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_user.会員.姓
     *
     * @mbg.generated
     */
    private String 姓;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_user.会員.名
     *
     * @mbg.generated
     */
    private String 名;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_user.会員.パスワード
     *
     * @mbg.generated
     */
    private String パスワード;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_user.会員.役割
     *
     * @mbg.generated
     */
    private String 役割;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_user.会員.登録日時
     *
     * @mbg.generated
     */
    private Date 登録日時;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_user.会員.会員番号
     *
     * @return the value of service_user.会員.会員番号
     * @mbg.generated
     */
    public String get会員番号() {
        return 会員番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_user.会員.会員番号
     *
     * @param 会員番号 the value for service_user.会員.会員番号
     * @mbg.generated
     */
    public void set会員番号(String 会員番号) {
        this.会員番号 = 会員番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_user.会員.姓
     *
     * @return the value of service_user.会員.姓
     * @mbg.generated
     */
    public String get姓() {
        return 姓;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_user.会員.姓
     *
     * @param 姓 the value for service_user.会員.姓
     * @mbg.generated
     */
    public void set姓(String 姓) {
        this.姓 = 姓;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_user.会員.名
     *
     * @return the value of service_user.会員.名
     * @mbg.generated
     */
    public String get名() {
        return 名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_user.会員.名
     *
     * @param 名 the value for service_user.会員.名
     * @mbg.generated
     */
    public void set名(String 名) {
        this.名 = 名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_user.会員.パスワード
     *
     * @return the value of service_user.会員.パスワード
     * @mbg.generated
     */
    public String getパスワード() {
        return パスワード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_user.会員.パスワード
     *
     * @param パスワード the value for service_user.会員.パスワード
     * @mbg.generated
     */
    public void setパスワード(String パスワード) {
        this.パスワード = パスワード;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_user.会員.役割
     *
     * @return the value of service_user.会員.役割
     * @mbg.generated
     */
    public String get役割() {
        return 役割;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_user.会員.役割
     *
     * @param 役割 the value for service_user.会員.役割
     * @mbg.generated
     */
    public void set役割(String 役割) {
        this.役割 = 役割;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_user.会員.登録日時
     *
     * @return the value of service_user.会員.登録日時
     * @mbg.generated
     */
    public Date get登録日時() {
        return 登録日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_user.会員.登録日時
     *
     * @param 登録日時 the value for service_user.会員.登録日時
     * @mbg.generated
     */
    public void set登録日時(Date 登録日時) {
        this.登録日時 = 登録日時;
    }
}
