package mrs.domain.model.autogen.reserve;

import java.util.Date;

public class 予約可能会議室 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.予約可能会議室.予約日
     *
     * @mbg.generated
     */
    private Date 予約日;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.予約可能会議室.会議室番号
     *
     * @mbg.generated
     */
    private Integer 会議室番号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve.予約可能会議室.登録日時
     *
     * @mbg.generated
     */
    private Date 登録日時;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.予約可能会議室.予約日
     *
     * @return the value of reserve.予約可能会議室.予約日
     * @mbg.generated
     */
    public Date get予約日() {
        return 予約日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.予約可能会議室.予約日
     *
     * @param 予約日 the value for reserve.予約可能会議室.予約日
     * @mbg.generated
     */
    public void set予約日(Date 予約日) {
        this.予約日 = 予約日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.予約可能会議室.会議室番号
     *
     * @return the value of reserve.予約可能会議室.会議室番号
     * @mbg.generated
     */
    public Integer get会議室番号() {
        return 会議室番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.予約可能会議室.会議室番号
     *
     * @param 会議室番号 the value for reserve.予約可能会議室.会議室番号
     * @mbg.generated
     */
    public void set会議室番号(Integer 会議室番号) {
        this.会議室番号 = 会議室番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve.予約可能会議室.登録日時
     *
     * @return the value of reserve.予約可能会議室.登録日時
     * @mbg.generated
     */
    public Date get登録日時() {
        return 登録日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve.予約可能会議室.登録日時
     *
     * @param 登録日時 the value for reserve.予約可能会議室.登録日時
     * @mbg.generated
     */
    public void set登録日時(Date 登録日時) {
        this.登録日時 = 登録日時;
    }
}
