package mrs.infrastructure.datasource.autogen.reservation;

import mrs.domain.model.autogen.reservation.予約可能会議室;
import org.apache.ibatis.annotations.*;

import java.util.Date;

public interface 予約可能会議室Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation.予約可能会議室
     *
     * @mbg.generated
     */
    @Delete({
            "delete from reservation.予約可能会議室",
            "where 予約日 = #{予約日,jdbcType=DATE}",
            "and 会議室番号 = #{会議室番号,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("予約日") Date 予約日, @Param("会議室番号") Integer 会議室番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation.予約可能会議室
     *
     * @mbg.generated
     */
    @Insert({
            "insert into reservation.予約可能会議室 (予約日, 会議室番号, ",
            "登録日時)",
            "values (#{予約日,jdbcType=DATE}, #{会議室番号,jdbcType=INTEGER}, ",
            "#{登録日時,jdbcType=TIMESTAMP})"
    })
    int insert(予約可能会議室 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation.予約可能会議室
     *
     * @mbg.generated
     */
    int insertSelective(予約可能会議室 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation.予約可能会議室
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "予約日, 会議室番号, 登録日時",
            "from reservation.予約可能会議室",
            "where 予約日 = #{予約日,jdbcType=DATE}",
            "and 会議室番号 = #{会議室番号,jdbcType=INTEGER}"
    })
    @ResultMap("mrs.infrastructure.datasource.autogen.reservation.予約可能会議室Mapper.BaseResultMap")
    予約可能会議室 selectByPrimaryKey(@Param("予約日") Date 予約日, @Param("会議室番号") Integer 会議室番号);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation.予約可能会議室
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(予約可能会議室 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation.予約可能会議室
     *
     * @mbg.generated
     */
    @Update({
            "update reservation.予約可能会議室",
            "set 登録日時 = #{登録日時,jdbcType=TIMESTAMP}",
            "where 予約日 = #{予約日,jdbcType=DATE}",
            "and 会議室番号 = #{会議室番号,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(予約可能会議室 record);
}
