package mrs.domain.model.autogen.reservation;

import java.util.Date;

public class 予約 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.予約番号
     *
     * @mbg.generated
     */
    private Integer 予約番号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.予約終了時間
     *
     * @mbg.generated
     */
    private Date 予約終了時間;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.予約開始時間
     *
     * @mbg.generated
     */
    private Date 予約開始時間;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.予約日
     *
     * @mbg.generated
     */
    private Date 予約日;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.会議室番号
     *
     * @mbg.generated
     */
    private Integer 会議室番号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.会員番号
     *
     * @mbg.generated
     */
    private String 会員番号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.予約.登録日時
     *
     * @mbg.generated
     */
    private Date 登録日時;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.予約番号
     *
     * @return the value of reservation.予約.予約番号
     * @mbg.generated
     */
    public Integer get予約番号() {
        return 予約番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.予約番号
     *
     * @param 予約番号 the value for reservation.予約.予約番号
     * @mbg.generated
     */
    public void set予約番号(Integer 予約番号) {
        this.予約番号 = 予約番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.予約終了時間
     *
     * @return the value of reservation.予約.予約終了時間
     * @mbg.generated
     */
    public Date get予約終了時間() {
        return 予約終了時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.予約終了時間
     *
     * @param 予約終了時間 the value for reservation.予約.予約終了時間
     * @mbg.generated
     */
    public void set予約終了時間(Date 予約終了時間) {
        this.予約終了時間 = 予約終了時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.予約開始時間
     *
     * @return the value of reservation.予約.予約開始時間
     * @mbg.generated
     */
    public Date get予約開始時間() {
        return 予約開始時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.予約開始時間
     *
     * @param 予約開始時間 the value for reservation.予約.予約開始時間
     * @mbg.generated
     */
    public void set予約開始時間(Date 予約開始時間) {
        this.予約開始時間 = 予約開始時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.予約日
     *
     * @return the value of reservation.予約.予約日
     * @mbg.generated
     */
    public Date get予約日() {
        return 予約日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.予約日
     *
     * @param 予約日 the value for reservation.予約.予約日
     * @mbg.generated
     */
    public void set予約日(Date 予約日) {
        this.予約日 = 予約日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.会議室番号
     *
     * @return the value of reservation.予約.会議室番号
     * @mbg.generated
     */
    public Integer get会議室番号() {
        return 会議室番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.会議室番号
     *
     * @param 会議室番号 the value for reservation.予約.会議室番号
     * @mbg.generated
     */
    public void set会議室番号(Integer 会議室番号) {
        this.会議室番号 = 会議室番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.会員番号
     *
     * @return the value of reservation.予約.会員番号
     * @mbg.generated
     */
    public String get会員番号() {
        return 会員番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.会員番号
     *
     * @param 会員番号 the value for reservation.予約.会員番号
     * @mbg.generated
     */
    public void set会員番号(String 会員番号) {
        this.会員番号 = 会員番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.予約.登録日時
     *
     * @return the value of reservation.予約.登録日時
     * @mbg.generated
     */
    public Date get登録日時() {
        return 登録日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.予約.登録日時
     *
     * @param 登録日時 the value for reservation.予約.登録日時
     * @mbg.generated
     */
    public void set登録日時(Date 登録日時) {
        this.登録日時 = 登録日時;
    }
}
