package mrs.domain.model.autogen.reservation;

import java.util.Date;

public class 会議室 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.会議室.会議室番号
     *
     * @mbg.generated
     */
    private Integer 会議室番号;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.会議室.会議室名
     *
     * @mbg.generated
     */
    private String 会議室名;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reservation.会議室.登録日時
     *
     * @mbg.generated
     */
    private Date 登録日時;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.会議室.会議室番号
     *
     * @return the value of reservation.会議室.会議室番号
     * @mbg.generated
     */
    public Integer get会議室番号() {
        return 会議室番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.会議室.会議室番号
     *
     * @param 会議室番号 the value for reservation.会議室.会議室番号
     * @mbg.generated
     */
    public void set会議室番号(Integer 会議室番号) {
        this.会議室番号 = 会議室番号;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.会議室.会議室名
     *
     * @return the value of reservation.会議室.会議室名
     * @mbg.generated
     */
    public String get会議室名() {
        return 会議室名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.会議室.会議室名
     *
     * @param 会議室名 the value for reservation.会議室.会議室名
     * @mbg.generated
     */
    public void set会議室名(String 会議室名) {
        this.会議室名 = 会議室名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reservation.会議室.登録日時
     *
     * @return the value of reservation.会議室.登録日時
     * @mbg.generated
     */
    public Date get登録日時() {
        return 登録日時;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reservation.会議室.登録日時
     *
     * @param 登録日時 the value for reservation.会議室.登録日時
     * @mbg.generated
     */
    public void set登録日時(Date 登録日時) {
        this.登録日時 = 登録日時;
    }
}
