package mrs.infrastructure.datasource.autogen.sample;

import mrs.domain.model.autogen.sample.Todo;
import mrs.domain.model.autogen.sample.TodoExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component("todoMapperAutogen")
public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    long countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    @Delete({
            "delete from sample.todo",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    @Insert({
            "insert into sample.todo (id, title, ",
            "details, finished)",
            "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
            "#{details,jdbcType=VARCHAR}, #{finished,jdbcType=BIT})"
    })
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, title, details, finished",
            "from sample.todo",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("mrs.infrastructure.datasource.autogen.sample.TodoMapper.BaseResultMap")
    Todo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample.todo
     *
     * @mbg.generated
     */
    @Update({
            "update sample.todo",
            "set title = #{title,jdbcType=VARCHAR},",
            "details = #{details,jdbcType=VARCHAR},",
            "finished = #{finished,jdbcType=BIT}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Todo record);
}
